variables:
  IMAGE_BASE: registry.gitlab.com/skn0tt/vplan
  UI_IMAGE: $IMAGE_BASE/ui:$CI_COMMIT_REF_NAME
  API_IMAGE: $IMAGE_BASE/api:$CI_COMMIT_REF_NAME

stages:
  - test
  - build
  - release
  - deploy

build_docs:
  stage: deploy
  script:
  - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.com/api/v4/projects/skn0tt%2Fvplan-deployments/trigger/pipeline
#
# Test
#
.test:unit:
  image: node:9
  stage: test
  before_script:
    - yarn
  script:
    - yarn test:coverage
  artifacts:
    paths:
      - coverage/lcov-report/
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

#
# Build
#
.Build API:
  image: skn0tt/dind-make
  stage: build
  services:
    - docker:dind
  tags:
    - docker
  only:
    - master
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
  script:
    - cd packages/api
    - make build IMAGE_TAG=$API_IMAGE
    - docker push $API_IMAGE

.Build UI:
  image: skn0tt/dind-make
  stage: build
  services:
    - docker:dind
  tags:
    - docker
  only:
    - master
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
  script:
    - cd packages/ui
    - make build IMAGE_TAG=$UI_IMAGE
    - docker push $UI_IMAGE

# Documentation
.Docs:
  image: python
  stage: build
  only:
    - master
  before_script:
    - pip install -r requirements.txt
  script:
    - mkdocs build
  artifacts:
    paths:
      - site/


# Build App
.app:ema:
  image: farwayer/react-native
  stage: release
  artifacts:
    paths:
      - ./packages/app/android/app/build/outputs/apk/release/
  only:
    - master
  only:
    - tags
  before_script:
    - yarn
  script:
    - cd packages/app
    # Gradle Properties
    - echo $KEYSTORE_GRADLE_PROPERTIES | base64 -d >> ./android/gradle.properties
    # Keystore
    - echo $KEYSTORE | base64 -d > ./android/app/vplan-app.keystore
    - API_BASEURL=https://vplan.ema-vplan.de/api IMPRINT_URL=https://www.ema-bonn.de/index.php/service/neuigkeiten/350-impressum yarn release:android:ci

# Coverage Pages
.pages:
  stage: release
  dependencies:
    - Docs
  script:
    - mv site/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
