version: '3'

services:

  ui:
    environment:
      LETSENCRYPT_HOST: ${HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

  api:
    environment:
      NODE_ENV: "production"
      LETSENCRYPT_HOST: ${HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

  nginx-proxy:
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    volumes:
      - "certs:/etc/nginx/certs"
      - "vhost:/etc/nginx/vhost.d"
      - "html:/usr/share/nginx/html"

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "certs:/etc/nginx/certs"
      - "vhost:/etc/nginx/vhost.d"
      - "html:/usr/share/nginx/html"

volumes:
  certs:
  vhost:
  html:

