version: "3"

services:
  
  redis:
    image: redis
    volumes:
      - data:/data
  
  nginx-proxy:
    image: joshtrow/nginx-proxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    restart: always
    depends_on:
      - api
      - ui
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"

  api:
    image: registry.gitlab.com/skn0tt/vplan/api:master
    depends_on:
      - redis
    environment:
      - PASSWORD
      - NODE_ENV=production
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PATH=/api/
      - VIRTUAL_PORT=3000

  ui:
    image: registry.gitlab.com/skn0tt/vplan/ui:master
    environment:
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PATH=/
      - VIRTUAL_PORT=80

volumes:
  data:
