version: "3"

services:
  
  redis:
    image: redis:alpine
    volumes:
      - data:/data
  
  nginx-proxy:
    image: joshtrow/nginx-proxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    restart: always
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"

  api:
    image: registry.gitlab.com/skn0tt/vplan/vplan-api
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PATH=/api/
      - VIRTUAL_PORT=3000

  ui:
    image: registry.gitlab.com/skn0tt/vplan/vplan-ui
    depends_on:
      - api
    environment:
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PATH=/
      - VIRTUAL_PORT=80

volumes:
  data:
