export default `
<html>
<head>
<title>Untis 2018 Vertretungsplan</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta http-equiv="expires" content="0">
<style type="text/css">

body { margin-top: 0px; margin-left: 20px; margin-right: 20px;
background: #fff; color: #272727; font: 80% Arial, Helvetica, sans-serif; }

h1 { color: #ee7f00; font-size: 150%; font-weight: normal;}
h1 strong { font-size: 200%; font-weight: normal; }
h2 { font-size: 125%;}

h1, h2 { margin: 0; padding: 0;}

th { background: #000; color: #fff; }
table.mon_list th, td { padding: 8px 4px;}


.mon_title 
{ 
	font-weight: bold; 
	font-size: 120%; 
	clear: both; 
	margin: 0; 
}

.inline_header
{
	font-weight: bold; 
}

table.info
{
	color: #000000; 
	font-size: 100%;
	border: 1px;
	border-style:solid;
	border-collapse:collapse;
	padding: 8px 4px;
}

table.mon_list
{
	color: #000000; 
	width: 100%; 
	font-size: 100%;
	border: 1px;
	border-style:solid;
	border-collapse:collapse;
}

table.mon_head
{
	color: #000000; 
	width: 100%; 
	font-size: 100%;
}

td.info,
th.list,
td.list,
tr.list
{
	border: 1px;
	border-style: solid;
	border-color: black;
	margin: 0px;
	border-collapse:collapse;
	padding: 3px;
}

tr.odd { background: #fad3a6; }
tr.even { background: #fdecd9; }

</style>
<meta name="generator" content="Untis 2018">
<meta name="company" content="Gruber &amp; Petters Software, A-2000 Stockerau, Austria, www.untis.at">
</head>

<body>
<table class="mon_head">
    <tr>
        <td valign="bottom"><h1><strong>Untis</strong> 2018 <!-- Info-Stundenplan --></h1></td>
        <td valign="bottom"></td>
        <td align="right" valign="bottom">
            <p>E.-M.-ARNDT-GYMNASIUM BONN <span style="width:10px">&nbsp;</span> D-53115, ENDENICHER ALLEE 1<br />
            Schuljahr 17/18 - HJ 2<span style="width:10px">&nbsp;</span>Stundenplan g�ltig ab 19.02.2018 <span style="width:10px">&nbsp;</span> Stand: 08.03.2018 12:37</p>
        </td>
    </tr>
</table>

<center>
<div class="mon_title">9.3.2018 Freitag, Woche B</div>
<table class="mon_list" >
<tr class='list'><th class="list">&nbsp;</th><th class="list">&nbsp;</th><th class="list">&nbsp;</th><th class="list" align="center">Ver-</th><th class="list">&nbsp;</th><th class="list">&nbsp;</th><th class="list">&nbsp;</th><th class="list" align="center">statt</th><th class="list" align="center">statt</th><th class="list" align="center" width='30'>Bemerk.</th><th class="list" align="center">&nbsp;</th></tr>
<tr class='list'><th class="list" align="center">Art</th><th class="list" align="center">Datum</th><th class="list" align="center">Std.</th><th class="list" align="center">treter</th><th class="list" align="center">Fach</th><th class="list" align="center" width='17'>Klasse(n)</th><th class="list" align="center">Raum</th><th class="list" align="center">Lehrer</th><th class="list" align="center">Raum</th><th class="list" align="center" width='30'>Sch�ler</th><th class="list" align="center" width='5'>Entf.</th></tr>
<tr class='list odd'><td class="list inline_header" colspan="11" >GL</td></tr>
<tr class='list even'><td class="list" align="center" style="background-color: #FFFFFF" ><span style="color: #FF0000">Entfall</span></td><td class="list" align="center" style="background-color: #FFFFFF" ><span style="color: #FF0000">9.3.</span></td><td class="list" align="center" style="background-color: #FFFFFF" ><span style="color: #FF0000">3</span></td><td class="list" align="center" style="background-color: #FFFFFF" ><span style="color: #FF0000">---</span></td><td class="list" align="center" style="background-color: #FFFFFF" ><span style="color: #FF0000">---</span></td><td class="list" align="center" style="background-color: #FFFFFF" ><span style="color: #FF0000">GL</span></td><td class="list" align="center" style="background-color: #FFFFFF" ><span style="color: #FF0000">---</span></td><td class="list" align="center" style="background-color: #FFFFFF" ><span style="color: #FF0000">H�H</span></td><td class="list" align="center" style="background-color: #FFFFFF" ><span style="color: #FF0000">E203</span></td><td class="list" style="background-color: #FFFFFF" >&nbsp;</td><td class="list" align="center" style="background-color: #FFFFFF" ><span style="color: #FF0000">x</span></td></tr>
<tr class='list odd'><td class="list" align="center" style="background-color: #FFFFFF" ><span style="color: #FF0000">Entfall</span></td><td class="list" align="center" style="background-color: #FFFFFF" ><span style="color: #FF0000">9.3.</span></td><td class="list" align="center" style="background-color: #FFFFFF" ><span style="color: #FF0000">4</span></td><td class="list" align="center" style="background-color: #FFFFFF" ><span style="color: #FF0000">---</span></td><td class="list" align="center" style="background-color: #FFFFFF" ><span style="color: #FF0000">---</span></td><td class="list" align="center" style="background-color: #FFFFFF" ><span style="color: #FF0000">GL</span></td><td class="list" align="center" style="background-color: #FFFFFF" ><span style="color: #FF0000">---</span></td><td class="list" align="center" style="background-color: #FFFFFF" ><span style="color: #FF0000">H�H</span></td><td class="list" align="center" style="background-color: #FFFFFF" ><span style="color: #FF0000">E202</span></td><td class="list" style="background-color: #FFFFFF" >&nbsp;</td><td class="list" align="center" style="background-color: #FFFFFF" ><span style="color: #FF0000">x</span></td></tr>
<tr class='list even'><td class="list inline_header" colspan="11" >Q2</td></tr>
<tr class='list odd'><td class="list" align="center" style="background-color: #FFFFFF" >EVA</td><td class="list" align="center" style="background-color: #FFFFFF" >9.3.</td><td class="list" align="center" style="background-color: #FFFFFF" >1 - 2</td><td class="list" align="center" style="background-color: #FFFFFF" >+</td><td class="list" align="center" style="background-color: #FFFFFF" >M  G2</td><td class="list" align="center" style="background-color: #FFFFFF" >Q2</td><td class="list" align="center" style="background-color: #FFFFFF" >A003</td><td class="list" align="center" style="background-color: #FFFFFF" >WER</td><td class="list" align="center" style="background-color: #FFFFFF" >A003</td><td class="list" align="center">&nbsp;</td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list even'><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">Sondereins.</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">9.3.</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">1 - 2</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">KLI</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">N-Schr.</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">Q2</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">OStR</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">&nbsp;</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">&nbsp;</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">&nbsp;</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">&nbsp;</span></td></tr>
<tr class='list odd'><td class="list" align="center" style="background-color: #FFFFFF" >EVA</td><td class="list" align="center" style="background-color: #FFFFFF" >9.3.</td><td class="list" align="center" style="background-color: #FFFFFF" >1 - 2</td><td class="list" align="center" style="background-color: #FFFFFF" >+</td><td class="list" align="center" style="background-color: #FFFFFF" >GE Z1</td><td class="list" align="center" style="background-color: #FFFFFF" >Q2</td><td class="list" align="center" style="background-color: #FFFFFF" >A103</td><td class="list" align="center" style="background-color: #FFFFFF" >BAR</td><td class="list" align="center" style="background-color: #FFFFFF" >A103</td><td class="list" align="center">&nbsp;</td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list even'><td class="list" align="center"><span style="color: #0000FF">Raum-Vtr.</span></td><td class="list" align="center"><span style="color: #0000FF">9.3.</span></td><td class="list" align="center"><span style="color: #0000FF">3</span></td><td class="list" align="center"><span style="color: #0000FF">GER</span></td><td class="list" align="center"><span style="color: #0000FF">E  G1</span></td><td class="list" align="center"><span style="color: #0000FF">Q2</span></td><td class="list" align="center"><span style="color: #0000FF">A103</span></td><td class="list" align="center"><span style="color: #0000FF">GER</span></td><td class="list" align="center"><span style="color: #0000FF">A106</span></td><td class="list" align="center">&nbsp;</td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list odd'><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">Sondereins.</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">9.3.</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">3</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">K�H</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">N-Schr.</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">Q2</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">OStR</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">&nbsp;</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">&nbsp;</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">&nbsp;</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">&nbsp;</span></td></tr>
<tr class='list even'><td class="list" align="center" style="background-color: #FFFFFF" >EVA</td><td class="list" align="center" style="background-color: #FFFFFF" >9.3.</td><td class="list" align="center" style="background-color: #FFFFFF" >4</td><td class="list" align="center" style="background-color: #FFFFFF" >+</td><td class="list" align="center" style="background-color: #FFFFFF" >PH G1</td><td class="list" align="center" style="background-color: #FFFFFF" >Q2</td><td class="list" align="center" style="background-color: #FFFFFF" >A-115</td><td class="list" align="center" style="background-color: #FFFFFF" >WET</td><td class="list" align="center" style="background-color: #FFFFFF" >A-115</td><td class="list" align="center">&nbsp;</td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list odd'><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">Sondereins.</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">9.3.</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">4</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">STI</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">N-Schr.</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">Q2</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">OStR</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">&nbsp;</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">&nbsp;</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">&nbsp;</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">&nbsp;</span></td></tr>
<tr class='list even'><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">Sondereins.</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">9.3.</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">5</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">WIL</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">N-Schr.</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">Q2</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">OStR</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">&nbsp;</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">&nbsp;</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">&nbsp;</span></td><td class="list" align="center" style="background-color: #CECECE" ><span style="color: #000080">&nbsp;</span></td></tr>
<tr class='list odd'><td class="list inline_header" colspan="11" >Q1</td></tr>
<tr class='list even'><td class="list" align="center" style="background-color: #FFFFFF" >EVA</td><td class="list" align="center" style="background-color: #FFFFFF" >9.3.</td><td class="list" align="center" style="background-color: #FFFFFF" >1 - 2</td><td class="list" align="center" style="background-color: #FFFFFF" >+</td><td class="list" align="center" style="background-color: #FFFFFF" >---</td><td class="list" align="center" style="background-color: #FFFFFF" >Q1</td><td class="list" align="center" style="background-color: #FFFFFF" >---</td><td class="list" align="center" style="background-color: #FFFFFF" >FRC</td><td class="list" align="center" style="background-color: #FFFFFF" >A107</td><td class="list" align="center">&nbsp;</td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list odd'><td class="list" align="center" style="background-color: #FFFFFF" >EVA</td><td class="list" align="center" style="background-color: #FFFFFF" >9.3.</td><td class="list" align="center" style="background-color: #FFFFFF" >1 - 2</td><td class="list" align="center" style="background-color: #FFFFFF" >+</td><td class="list" align="center" style="background-color: #FFFFFF" >---</td><td class="list" align="center" style="background-color: #FFFFFF" >Q1</td><td class="list" align="center" style="background-color: #FFFFFF" >---</td><td class="list" align="center" style="background-color: #FFFFFF" >UHL</td><td class="list" align="center" style="background-color: #FFFFFF" >B007</td><td class="list" align="center">&nbsp;</td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list even'><td class="list" align="center" style="background-color: #FFFFFF" >EVA</td><td class="list" align="center" style="background-color: #FFFFFF" >9.3.</td><td class="list" align="center" style="background-color: #FFFFFF" >1 - 2</td><td class="list" align="center" style="background-color: #FFFFFF" >+</td><td class="list" align="center" style="background-color: #FFFFFF" >---</td><td class="list" align="center" style="background-color: #FFFFFF" >Q1</td><td class="list" align="center" style="background-color: #FFFFFF" >---</td><td class="list" align="center" style="background-color: #FFFFFF" >JUN</td><td class="list" align="center" style="background-color: #FFFFFF" >A104</td><td class="list" align="center">&nbsp;</td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list odd'><td class="list" align="center" style="background-color: #FFFFFF" >EVA</td><td class="list" align="center" style="background-color: #FFFFFF" >9.3.</td><td class="list" align="center" style="background-color: #FFFFFF" >1 - 2</td><td class="list" align="center" style="background-color: #FFFFFF" >+</td><td class="list" align="center" style="background-color: #FFFFFF" >---</td><td class="list" align="center" style="background-color: #FFFFFF" >Q1</td><td class="list" align="center" style="background-color: #FFFFFF" >---</td><td class="list" align="center" style="background-color: #FFFFFF" >KLI</td><td class="list" align="center" style="background-color: #FFFFFF" >F101</td><td class="list" align="center">&nbsp;</td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list even'><td class="list" align="center"><span style="color: #010101">Klausur</span></td><td class="list" align="center"><span style="color: #010101">9.3.</span></td><td class="list" align="center"><span style="color: #010101">1 - 2</span></td><td class="list" align="center"><span style="color: #010101">JUN</span></td><td class="list" align="center"><span style="color: #010101">SW G1</span></td><td class="list" align="center"><span style="color: #010101">Q1</span></td><td class="list" align="center"><span style="color: #010101">OStR</span></td><td class="list">&nbsp;</td><td class="list">&nbsp;</td><td class="list" align="center"><span style="color: #010101">Klausur</span></td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list odd'><td class="list" align="center"><span style="color: #010101">Klausur</span></td><td class="list" align="center"><span style="color: #010101">9.3.</span></td><td class="list" align="center"><span style="color: #010101">1 - 2</span></td><td class="list" align="center"><span style="color: #010101">JUN</span></td><td class="list" align="center"><span style="color: #010101">BIBG1</span></td><td class="list" align="center"><span style="color: #010101">Q1</span></td><td class="list" align="center"><span style="color: #010101">OStR</span></td><td class="list">&nbsp;</td><td class="list">&nbsp;</td><td class="list" align="center"><span style="color: #010101">Klausur</span></td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list even'><td class="list" align="center"><span style="color: #010101">Klausur</span></td><td class="list" align="center"><span style="color: #010101">9.3.</span></td><td class="list" align="center"><span style="color: #010101">1 - 2</span></td><td class="list" align="center"><span style="color: #010101">UHL</span></td><td class="list" align="center"><span style="color: #010101">BI G1</span></td><td class="list" align="center"><span style="color: #010101">Q1</span></td><td class="list" align="center"><span style="color: #010101">B007</span></td><td class="list">&nbsp;</td><td class="list">&nbsp;</td><td class="list" align="center"><span style="color: #010101">Klausur</span></td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list odd'><td class="list" align="center"><span style="color: #010101">Klausur</span></td><td class="list" align="center"><span style="color: #010101">9.3.</span></td><td class="list" align="center"><span style="color: #010101">1 - 2</span></td><td class="list" align="center"><span style="color: #010101">JUN</span></td><td class="list" align="center"><span style="color: #010101">PH G1</span></td><td class="list" align="center"><span style="color: #010101">Q1</span></td><td class="list" align="center"><span style="color: #010101">OStR</span></td><td class="list">&nbsp;</td><td class="list">&nbsp;</td><td class="list" align="center"><span style="color: #010101">Klausur</span></td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list even'><td class="list" align="center"><span style="color: #010101">Klausur</span></td><td class="list" align="center"><span style="color: #010101">9.3.</span></td><td class="list" align="center"><span style="color: #010101">1 - 3</span></td><td class="list" align="center"><span style="color: #010101">FRC</span></td><td class="list" align="center"><span style="color: #010101">E  G4</span></td><td class="list" align="center"><span style="color: #010101">Q1</span></td><td class="list" align="center"><span style="color: #010101">A107</span></td><td class="list">&nbsp;</td><td class="list">&nbsp;</td><td class="list" align="center"><span style="color: #010101">Klausur</span></td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list odd'><td class="list" align="center"><span style="color: #010101">Klausur</span></td><td class="list" align="center"><span style="color: #010101">9.3.</span></td><td class="list" align="center"><span style="color: #010101">1 - 2</span></td><td class="list" align="center"><span style="color: #010101">KLI</span></td><td class="list" align="center"><span style="color: #010101">GE G3</span></td><td class="list" align="center"><span style="color: #010101">Q1</span></td><td class="list" align="center"><span style="color: #010101">OStR</span></td><td class="list">&nbsp;</td><td class="list">&nbsp;</td><td class="list" align="center"><span style="color: #010101">Klausur</span></td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list even'><td class="list" align="center"><span style="color: #0000FF">Raum-Vtr.</span></td><td class="list" align="center"><span style="color: #0000FF">9.3.</span></td><td class="list" align="center"><span style="color: #0000FF">3 - 4</span></td><td class="list" align="center"><span style="color: #0000FF">OST</span></td><td class="list" align="center"><span style="color: #0000FF">D  G2</span></td><td class="list" align="center"><span style="color: #0000FF">Q1</span></td><td class="list" align="center"><span style="color: #0000FF">F002</span></td><td class="list" align="center"><span style="color: #0000FF">OST</span></td><td class="list" align="center"><span style="color: #0000FF">A-116</span></td><td class="list" align="center">&nbsp;</td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list odd'><td class="list" align="center"><span style="color: #010101">Klausur</span></td><td class="list" align="center"><span style="color: #010101">9.3.</span></td><td class="list" align="center"><span style="color: #010101">3</span></td><td class="list" align="center"><span style="color: #010101">K�H</span></td><td class="list" align="center"><span style="color: #010101">GE G3</span></td><td class="list" align="center"><span style="color: #010101">Q1</span></td><td class="list" align="center"><span style="color: #010101">OStR</span></td><td class="list">&nbsp;</td><td class="list">&nbsp;</td><td class="list" align="center"><span style="color: #010101">Klausur</span></td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list even'><td class="list" align="center" style="background-color: #FFFFFF" >EVA</td><td class="list" align="center" style="background-color: #FFFFFF" >9.3.</td><td class="list" align="center" style="background-color: #FFFFFF" >5 - 6</td><td class="list" align="center" style="background-color: #FFFFFF" >+</td><td class="list" align="center" style="background-color: #FFFFFF" >PH L1</td><td class="list" align="center" style="background-color: #FFFFFF" >Q1</td><td class="list" align="center" style="background-color: #FFFFFF" >B108</td><td class="list" align="center" style="background-color: #FFFFFF" >WET</td><td class="list" align="center" style="background-color: #FFFFFF" >B108</td><td class="list" align="center">&nbsp;</td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list odd'><td class="list" align="center" style="background-color: #FFFFFF" >EVA</td><td class="list" align="center" style="background-color: #FFFFFF" >9.3.</td><td class="list" align="center" style="background-color: #FFFFFF" >8 - 9</td><td class="list" align="center" style="background-color: #FFFFFF" >+</td><td class="list" align="center" style="background-color: #FFFFFF" >PX_PH1</td><td class="list" align="center" style="background-color: #FFFFFF" >Q1</td><td class="list" align="center" style="background-color: #FFFFFF" >B108</td><td class="list" align="center" style="background-color: #FFFFFF" >WET</td><td class="list" align="center" style="background-color: #FFFFFF" >B108</td><td class="list" align="center">&nbsp;</td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list even'><td class="list inline_header" colspan="11" >EF</td></tr>
<tr class='list odd'><td class="list" align="center">Betreuung</td><td class="list" align="center">9.3.</td><td class="list" align="center">3</td><td class="list" align="center">REI</td><td class="list" align="center">IF G1</td><td class="list" align="center">EF</td><td class="list" align="center">B110</td><td class="list" align="center">BEL</td><td class="list" align="center">B110</td><td class="list" align="center">&nbsp;</td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list even'><td class="list" align="center"><span style="color: #0000FF">Raum-Vtr.</span></td><td class="list" align="center"><span style="color: #0000FF">9.3.</span></td><td class="list" align="center"><span style="color: #0000FF">3 - 4</span></td><td class="list" align="center"><span style="color: #0000FF">M�L</span></td><td class="list" align="center"><span style="color: #0000FF">D  G3</span></td><td class="list" align="center"><span style="color: #0000FF">EF</span></td><td class="list" align="center"><span style="color: #0000FF">A106</span></td><td class="list" align="center"><span style="color: #0000FF">M�L</span></td><td class="list" align="center"><span style="color: #0000FF">A107</span></td><td class="list" align="center">&nbsp;</td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list odd'><td class="list" align="center" style="background-color: #FFFFFF" >Vertr.</td><td class="list" align="center" style="background-color: #FFFFFF" >9.3.</td><td class="list" align="center" style="background-color: #FFFFFF" >4</td><td class="list" align="center" style="background-color: #FFFFFF" >REI</td><td class="list" align="center" style="background-color: #FFFFFF" >IF G1</td><td class="list" align="center" style="background-color: #FFFFFF" >EF</td><td class="list" align="center" style="background-color: #FFFFFF" >B110</td><td class="list" align="center" style="background-color: #FFFFFF" >BEL</td><td class="list" align="center" style="background-color: #FFFFFF" >B110</td><td class="list" align="center">&nbsp;</td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list even'><td class="list inline_header" colspan="11" >9B</td></tr>
<tr class='list odd'><td class="list" align="center">Betreuung</td><td class="list" align="center">9.3.</td><td class="list" align="center">5</td><td class="list" align="center">DAH</td><td class="list" align="center">M</td><td class="list" align="center">9B</td><td class="list" align="center">A004</td><td class="list" align="center">BEL</td><td class="list" align="center">A004</td><td class="list" align="center">&nbsp;</td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list even'><td class="list" align="center" style="background-color: #FFFFFF" >Statt-Vertr.</td><td class="list" align="center" style="background-color: #FFFFFF" >9.3.</td><td class="list" align="center" style="background-color: #FFFFFF" >6</td><td class="list" align="center" style="background-color: #FFFFFF" >YOM</td><td class="list" align="center" style="background-color: #FFFFFF" >M</td><td class="list" align="center" style="background-color: #FFFFFF" >9B</td><td class="list" align="center" style="background-color: #FFFFFF" >A004</td><td class="list" align="center" style="background-color: #FFFFFF" >BEL</td><td class="list" align="center" style="background-color: #FFFFFF" >A004</td><td class="list" align="center">&nbsp;</td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list odd'><td class="list inline_header" colspan="11" >9A</td></tr>
<tr class='list even'><td class="list" align="center"><span style="color: #0000FF">Raum-Vtr.</span></td><td class="list" align="center"><span style="color: #0000FF">9.3.</span></td><td class="list" align="center"><span style="color: #0000FF">4</span></td><td class="list" align="center"><span style="color: #0000FF">GIT</span></td><td class="list" align="center"><span style="color: #0000FF">D</span></td><td class="list" align="center"><span style="color: #0000FF">9A</span></td><td class="list" align="center"><span style="color: #0000FF">A107</span></td><td class="list" align="center"><span style="color: #0000FF">GIT</span></td><td class="list" align="center"><span style="color: #0000FF">A106</span></td><td class="list" align="center">&nbsp;</td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list odd'><td class="list inline_header" colspan="11" >8A</td></tr>
<tr class='list even'><td class="list" align="center" style="background-color: #DBDAA6" ><span style="color: #800080">Statt-Vertr.</span></td><td class="list" align="center" style="background-color: #DBDAA6" ><span style="color: #800080">9.3.</span></td><td class="list" align="center" style="background-color: #DBDAA6" ><span style="color: #800080">1 - 2</span></td><td class="list" align="center" style="background-color: #DBDAA6" ><span style="color: #800080">KRE</span></td><td class="list" align="center" style="background-color: #DBDAA6" ><span style="color: #800080">M</span></td><td class="list" align="center" style="background-color: #DBDAA6" ><span style="color: #800080">8A</span></td><td class="list" align="center" style="background-color: #DBDAA6" ><span style="color: #800080">A105</span></td><td class="list" align="center" style="background-color: #DBDAA6" ><span style="color: #800080">BEL</span></td><td class="list" align="center" style="background-color: #DBDAA6" ><span style="color: #800080">A105</span></td><td class="list" align="center" style="background-color: #DBDAA6" ><span style="color: #800080">&nbsp;</span></td><td class="list" align="center" style="background-color: #DBDAA6" ><span style="color: #800080">&nbsp;</span></td></tr>
<tr class='list odd'><td class="list inline_header" colspan="11" >7C</td></tr>
<tr class='list even'><td class="list" align="center" style="background-color: #FFFFFF" >Vertr.</td><td class="list" align="center" style="background-color: #FFFFFF" >9.3.</td><td class="list" align="center" style="background-color: #FFFFFF" >3</td><td class="list" align="center" style="background-color: #FFFFFF" >HER</td><td class="list" align="center" style="background-color: #FFFFFF" >F6</td><td class="list" align="center" style="background-color: #FFFFFF" >7C</td><td class="list" align="center" style="background-color: #FFFFFF" >A208</td><td class="list" align="center" style="background-color: #FFFFFF" >BRI</td><td class="list" align="center" style="background-color: #FFFFFF" >A208</td><td class="list" align="center">&nbsp;</td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list odd'><td class="list inline_header" colspan="11" >6A</td></tr>
<tr class='list even'><td class="list" align="center" style="background-color: #FFFFFF" >Vertr.</td><td class="list" align="center" style="background-color: #FFFFFF" >9.3.</td><td class="list" align="center" style="background-color: #FFFFFF" >3</td><td class="list" align="center" style="background-color: #FFFFFF" >DAM</td><td class="list" align="center" style="background-color: #FFFFFF" >LQ</td><td class="list" align="center" style="background-color: #FFFFFF" >6A</td><td class="list" align="center" style="background-color: #FFFFFF" >E105</td><td class="list" align="center" style="background-color: #FFFFFF" >BAR</td><td class="list" align="center" style="background-color: #FFFFFF" >E105</td><td class="list" align="center">&nbsp;</td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list odd'><td class="list" align="center" style="background-color: #FFFFFF" >Vertr.</td><td class="list" align="center" style="background-color: #FFFFFF" >9.3.</td><td class="list" align="center" style="background-color: #FFFFFF" >5</td><td class="list" align="center" style="background-color: #FFFFFF" >OST</td><td class="list" align="center" style="background-color: #FFFFFF" >D</td><td class="list" align="center" style="background-color: #FFFFFF" >6A</td><td class="list" align="center" style="background-color: #FFFFFF" >E105</td><td class="list" align="center" style="background-color: #FFFFFF" >BAR</td><td class="list" align="center" style="background-color: #FFFFFF" >E105</td><td class="list" align="center">&nbsp;</td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list even'><td class="list" align="center" style="background-color: #FFFFFF" >Vertr.</td><td class="list" align="center" style="background-color: #FFFFFF" >9.3.</td><td class="list" align="center" style="background-color: #FFFFFF" >6</td><td class="list" align="center" style="background-color: #FFFFFF" >SCA</td><td class="list" align="center" style="background-color: #FFFFFF" >D</td><td class="list" align="center" style="background-color: #FFFFFF" >6A</td><td class="list" align="center" style="background-color: #FFFFFF" >E105</td><td class="list" align="center" style="background-color: #FFFFFF" >BAR</td><td class="list" align="center" style="background-color: #FFFFFF" >E105</td><td class="list" align="center">&nbsp;</td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list odd'><td class="list inline_header" colspan="11" >5B</td></tr>
<tr class='list even'><td class="list" align="center">Betreuung</td><td class="list" align="center">9.3.</td><td class="list" align="center">2</td><td class="list" align="center">WIL</td><td class="list" align="center">PK</td><td class="list" align="center">5B</td><td class="list" align="center">E203</td><td class="list" align="center">H�H</td><td class="list" align="center">E203</td><td class="list" align="center">&nbsp;</td><td class="list" align="center">&nbsp;</td></tr>
<tr class='list odd'><td class="list inline_header" colspan="11" >5A</td></tr>
<tr class='list even'><td class="list" align="center" style="background-color: #FFFFFF" >Statt-Vertr.</td><td class="list" align="center" style="background-color: #FFFFFF" >9.3.</td><td class="list" align="center" style="background-color: #FFFFFF" >5 - 6</td><td class="list" align="center" style="background-color: #FFFFFF" >SPI</td><td class="list" align="center" style="background-color: #FFFFFF" >MN</td><td class="list" align="center" style="background-color: #FFFFFF" >5A</td><td class="list" align="center" style="background-color: #FFFFFF" >E201</td><td class="list" align="center" style="background-color: #FFFFFF" >WER</td><td class="list" align="center" style="background-color: #FFFFFF" >E201</td><td class="list" align="center">&nbsp;</td><td class="list" align="center">&nbsp;</td></tr>
</table>
<p>
<font size="3" face="Arial">
Periode9   9.3.2018 B   2.Halbjahr   DB~1~2017-2018~1
</font></center>

<p><center><font face="Arial" size="2"><a href="http://www.untis.at" target="_blank" >Untis Stundenplan Software</a></font></center>
</body>
</html>

`;
